### Model de optimizare

In [1]:
from model import CamereVideo
import numpy as np
camereVideo = CamereVideo("./intrare.csv")

In [2]:
import time
import math
from tqdm import tqdm
solutii = []
start_time = time.time()
for i in tqdm(range(1000)):
    x = camereVideo.gen_nec(False)
    arie = camereVideo.F(x)
    solutii.append(np.hstack((x.flatten(), arie)))
timp = time.time()-start_time
n_inreg = np.array(solutii).shape[0]
print("\nTimp scurs: %.2f secunde / %d înregistrări" % (timp, n_inreg))
timp_t = (timp*n_inreg)/3600
print("Timp total pentru 1.000.000 înregistrări: %d ore %d minute" % (math.floor(timp_t), (timp_t-math.floor(timp_t))*60))

100%|██████████| 1000/1000 [00:13<00:00, 73.08it/s]
Timp scurs: 13.70 secunde / 1000 înregistrări
Timp total pentru 1.000.000 înregistrări: 3 ore 48 minute



In [3]:
x = camereVideo.gen_nec(False)
print("Necunoscută:", x.flatten(), '->', camereVideo.F(x))

Necunoscută: [11.39493602  4.55748469 10.39939467  3.71054938  7.10815816 11.83986702] -> 60.0


In [4]:
camereVideo.plot(x)

## Hill Climbing

In [5]:
from HillClimbing import HillClimbing
hc = HillClimbing(camereVideo, x=x, pas=0.5)
optim1 = hc.run_basic()
print(optim1, "Arie: ", hc.valoare(optim1))
camereVideo.plot(optim1.reshape((3,2)))

[11.39493602  4.55748469 10.39939467  3.71054938  7.10815816 11.83986702] Arie:  60.0


In [6]:
optim2 = hc.run_steep()
print(optim2, "Arie: ", hc.valoare(optim2))
camereVideo.plot(optim2.reshape((3,2)))

[11.39493602  4.55748469 10.39939467  3.71054938  7.10815816 11.83986702] Arie:  60.0


In [7]:
optim3 = hc.run_random()
print(optim3, "Arie: ", hc.valoare(optim3))
camereVideo.plot(optim3.reshape((3,2)))

[11.89493602  3.55748469  8.39939467  4.21054938  6.10815816  8.83986702] Arie:  69.0


## Simulated Annealing

In [8]:
from SimulatedAnnealing import SimulatedAnnealing
sa = SimulatedAnnealing(camereVideo, x=x, pas=0.5)
optim = sa.run()
print(optim, "Arie: ", sa.q(optim))
camereVideo.plot(optim.reshape((3,2)))

[10.39493602  4.05748469  9.89939467  3.71054938  7.10815816 10.83986702] Arie:  66.0
